#!/usr/bin/env bash
# Check if argument is provided
if [ $# -eq 0 ]; then
    # echo "Usage: ${0##*/} {IP_ADDRESS}"
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

IP_ADDRESS=$1

# Ping the IP address 5 times
ping -c 5 "$IP_ADDRESS"