#!/usr/bin/env bash
# Display all active IPv4 addresses on the machine
# ip -o -4 addr show | awk '{print $4}' | cut -d'/' -f1
# Alternative version using hostname
# hostname -I | tr ' ' '\n' | grep -v '^$'
# Use the ifconfig and grep to filter out IPv4 addresses
ifconfig | grep -w "inet" | awk '{print $2}'