#!/usr/bin/env bash
# Display all active IPv4 addresses on the machine
ip -o -4 addr show | awk '{print $4}' | cut -d'/' -f1
# Alternative version using hostname
hostname -I | tr ' ' '\n' | grep -v '^$'